### ISSUE TITLE
Riot API update

### ISSUE THREAD

**Issue by fawques** [aj-r/RiotNet#11]
Is there any plan to update RiotNet to the new v3 API?

https://discussion.developer.riotgames.com/articles/652/riot-games-api-v3.html
https://discussion.developer.riotgames.com/articles/1053/v1v2-90-day-deprecation-period-has-begun.html

**Comment by aj-r** [comment]
Thanks for the heads up! I have not been watching the API recently. I definitely want to update to V3, but I might not have time for a little while. You could always submit a PR though :). But let me know if you start working on it so we don't both work on the same thing.

**Comment by aj-r** [comment]
I've started working on this on branch `api-v3`.
