### ISSUE TITLE
VB.Net (No idea what I'm doing)

### ISSUE THREAD

**Issue by JoshPaulie** [aj-r/RiotNet#20]
`Dim client As New RiotClient`
`client.Settings.ApiKey = apikeyref`
`Dim r As Models.Summoner = Await client.GetSummonerBySummonerNameAsync("jaowsh")`

How is this not working? (The apikey is a dim at top.) I'm getting error with "await" and "client"

**Comment by JoshPaulie** [comment]
GOT IT. Needed the sub to be an async sub..silly me

**Comment by aj-r** [comment]
Great! I'm glad you were able to resolve it.
