### ISSUE TITLE
Missing values in MatchParticipantStats

### ISSUE THREAD

**Issue by TomTomB** [aj-r/RiotNet#24]
Hi,
the following properties are not included inside MatchParticipantStats:

perkPrimaryStyle
perkSubStyle

Other missing values are playerScore0 - playerScore9, but since they are not used / always 0, those are of no importance I´d guess.  

Cheers

**Comment by aj-r** [comment]
Those properties are not documented by Riot, which is probably why I missed them. You're right, though - they should be there.

I'll avoid implementing playerScore0 - playerScore9 for now, until Riot decides if they're going to use them properly or get rid of them.

**Comment by aj-r** [comment]
Fixed in 6.1.0
