### ISSUE TITLE
All the masteries are Ferocity

### ISSUE THREAD

**Issue by ghost** [aj-r/RiotNet#4]
when i access the masteries from the "GetStaticMasteries()", every mastery i get is ferocity, even doe it should be cunning or resolve.

**Comment by aj-r** [comment]
By default, the API does not include the `MasteryTree` property in the response (https://developer.riotgames.com/api/methods#!/1055/3625).

To get the mastery tree property, call the function like this:

`var masteryList = await client.GetStaticMasteriesAsync(masteryListData: new[] { "MasteryTree" });`

or

`var masteryList = await client.GetStaticMasteriesAsync(masteryListData: new[] { "all" });`

I think what's happening is the client is falling back to the default value (`Ferocity`) if the `MasteryTree` property is not included in the response. Maybe I should make that property nullable so it is clearer when it is not specified.

**Comment by aj-r** [comment]
I have created a new issue (#5) to make it clearer when values from the API are not specified. Closing this issue.
