### ISSUE TITLE
RiotNet.Test / RiotClientTests.cs / GetServerName_ShouldBeDefinedForAllRegions() is wrong

### ISSUE THREAD

**Issue by morbalint** [aj-r/RiotNet#7]
RiotNet.Test / RiotClientTests.cs / GetServerName_ShouldBeDefinedForAllRegions() tests for platformId. It should test for serverName.
 example correct implementation (too lazy for pull request XD, and idk if u even care about this anymore):  

``` C#
[Test]
public void GetServerName_ShouldBeDefinedForAllRegions()
{
    foreach (string server in from Region region in Enum.GetValues(typeof(Region)) select RiotClient.GetServerName(region))
    {
        Assert.That(server, Is.Not.Null.And.Not.Empty);
    }
}
```

**Comment by aj-r** [comment]
Good catch - thanks!
